### PR TITLE
Add support for changing the default icon set 

### PR DESCRIPTION
**Pull request by Livijn**
This is mostly to pick your brain. I don't know if you'd like something like this. For some reason when I clone your repo and then import it into my project I get an error: `ERROR in ../vue-fontawesome/index.es.js: Can't resolve 'core-js/modules/es...` so I haven't really tried if this works.

Before:

`<fa-icon :icon="['far', 'heart']" />`

After:

`<fa-icon icon="heart" />`

### CODE REVIEW

**Comment by christhofer** [comment]
I've made a pull request for this as well #243
The pull request was automatically close when the branch master is somehow got deleted.

Check out @robmadole 's answer there

**Comment by magicMustard** [comment]
How are we going with merging this?

**Comment by robmadole** [comment]
This will be part of Font Awesome 6 and will use a new API configuration option from the core project. We'll be releasing this functionality as part of the 6.0.0-beta1 release.

**Comment by jasonlundien** [comment]
I am going to go ahead and close this PR.  We have added [setting a default style in vue](https://fontawesome.com/docs/web/use-with/vue/dig-deeper#setting-a-default-style) with our V6 release.

Once the default style has been set:
`config.styleDefault = "duotone";`

You can use icon pretty close to the suggested:
```
<font-awesome-icon icon="dog" size="3x" />
<font-awesome-icon icon="cat" size="2x" flip="horizontal" />
```

**Pull request closed without merging**
