### PR TITLE
Added Vue as external dependency

### LINKED ISSUE #258: HMR not working in Vue CLI 4.5.6 with Vue 3 - Typescript
### Describe the bug
With my current setup of creating a new project with Vue CLI, whenever I directly import `FontAwesomeIcon` and globally create the component in `main.ts`, HMR stopped working. 
If I use custom Vue Component, it is working just fine.

#### Dependencies
1. @vue/cli 4.5.6
2. @cue/cli-service 4.5.0
3. typescript 3.9.3
4. @fortawesome/fontawesome-svg-core 1.2.30
5. @fortawesome/free-solid-svg-icons 5.14.0
6. @fortawesome/vue-fontawesome 3.0.0-1

**Expected behavior**
HMR reload normally after saving changes.

**main.ts**
```ts
import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import { store } from './store'

import './assets/styles/index.css'

import { library } from '@fortawesome/fontawesome-svg-core'
import { faSpinner } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(faSpinner)

const app = createApp(App)
app.use(store)
app.use(router)
app.component('fa', FontAwesomeIcon)
app.mount('#app')

```

**Console logs**

There's a weird second dev related notification of webpack in Chrome console.

image

### PR DESCRIPTION
**Pull request by viniciuslrangel**
Fixes #258

### CODE REVIEW

**Comment by dipasqualew** [comment]
Thank you! I was about to investigate the issue myself. Hopefully maintainers can merge this ASAP.

**Comment by dipasqualew** [comment]
@robmadole could this PR be checked whether it solves the issue & be merged?

HMR is quite important

**Comment by robmadole** [comment]
The `index.js` and `index.es.js` were removed in this PR, why was that?

**Comment by viniciuslrangel** [comment]
They were not removed. Vue was bundled together, when I added Vue as an external dependency, it was also removed from bundling. Now index.js has only 533 lines and index.es.js, 524

**Comment by robmadole** [comment]
Jeez. 🤦🏽‍♂️. Thank you. I'll get this merged and released now.

**Pull request merged**
