### PR TITLE
Vue 3 support

### LINKED ISSUE #230: Vue 3 support
**Is your feature request related to a problem? Please describe.**
Vue 3 is already in late beta and some of the deeper APIs are incompatible with Vue 2. It would be nice to have a Vue 3 compatible fontawesome component.

**Describe the solution you'd like**
Upgrade the component to use the new render APIs: https://github.com/vuejs/rfcs/pull/28

### PR DESCRIPTION
**Pull request by rigma**
With the eminent release of [Vue 3](https://github.com/vuejs/rfcs/issues/189), and because it's a requested feature in #230, this PR introduces Vue 3 support for `vue-fontawesome`.

# Changes made in the PR

## Converting functional components into stateful components

With the release of Vue 3, `{ functional: true }` [component option is removed](https://v3.vuejs.org/guide/migration/functional-components.html) and performances between functional and stateful components are now negligeable.

As recommanded in the migration guide, components are now stateful.

## Using `setup()` functions instead of `render()` functions

**⚠️ Breaking changes ⚠️**

In Vue 3, [render functions will no longer receives arguments](https://v3.vuejs.org/guide/migration/render-function-api.html). As a result, it can no longer access to `props` or `slots` and the `h` function shall be globally imported.

A more detailed explanation of the changes can be found in the related RFC: vuejs/rfcs#28.

Therefore, I've updated the conversion function from [`converter.js`](https://github.com/rigma/vue-fontawesome/blob/chore/vue-3-support/src/converter.js#L68) to return render functions that can be used with `setup()` method of a component.

## Refreshing example

I've rewritten the example to showcase the use of `vue-fontawesome` with Vue 3.

## Migrating Jest test cases

Now, the test cases are using `@vue/test-utils` in order to mount components.

Closes #230

### CODE REVIEW

**Comment by robmadole** [comment]
Amazing! Thanks @rigma. I will have some time in the next couple of weeks to look over this and move it forward.

**Comment by robmadole** [comment]
Alright, I'm focusing on this today. I expect to have an pre-release candidate out today from your work @rigma

**Comment by robmadole** [comment]
Hey, @rigma I'm prepped to merge this in but I introduced a couple of package lock conflicts. Do you think you can resolve those real quick? (The examples/vue-cli-webpack just needs to be deleted.) Otherwise if you don't have time I can open another PR and pull your commits over.

**Comment by robmadole** [comment]
@rigma porting this over to #249. I want to make sure I can get this released today!

**Comment by rigma** [comment]
No worries @robmadole! If you want me to do some changes, I can made it.

**Comment by robmadole** [comment]
Nope, you've done plenty! Thank you again.

**Pull request closed without merging**
