### PR TITLE
fix: Type definitions for Vue 3 Composition API

### PR DESCRIPTION
**Pull request by parkeyparker**
`FontAwesomeIcon` and other components needed to be of type `DefineComponent` for Vue 3 Composition API TypeScript support (as per #276). The type definitions for the component props also needed updating to denote required and optional props. 

Whilst checking which props were required it was noted that the `FontAwesomeLayer` component uses `fixedWidth` but the README and example use `full-width` so these have been updated to match the component code.

### CODE REVIEW

**Comment by robmadole** [comment]
Hey, thanks @parkeyparker. We'll take a look at this when we can.

**Comment by nielsvanvelzen** [comment]
Any updates on this PR? Recent changes to Volar (Vue extension for VSCode) show an error for the font awesome component and this PR fixes that.

**Comment by parkeyparker** [comment]
I've rebased my changes onto the latest code on the 3.x branch which should hopefully make it ready for review and merge. Any issues please let me know and I'll get them addressed as quick as I can.

**Comment by datrinh** [comment]
This is open since April... Our project build breaks due to this. What's stopping you from merging?

**Comment by plehnen** [comment]
Pleeeease merge this!

**Comment by dalirnet** [comment]
What's stopping you from merging?

**Review by jasonlundien — APPROVED** [review]

**Pull request merged**
