### PR TITLE
Added counter support for FontAwesomeLayersText

### PR DESCRIPTION
**Pull request by david-driscoll**
Also added inverse for `fa-inverse`.

Let me know if there are any changes needed.

### CODE REVIEW

**Comment by robmadole** [comment]
Fantastic! @david-driscoll sorry for the long silence but I'm digging through old emails now. Thank you for this. I'll carve some time to review and test this out and let you know. Really appreciate the work.

**Comment by robmadole** [comment]
Alright @david-driscoll this looks great. Would you be willing to [update the `README.md`](https://github.com/FortAwesome/vue-fontawesome#advanced)? I'll get this merged and released once we get that done.

**Comment by mgrinspan** [comment]
Any update on this? Sorry to impose but this would be very helpful for my current project

**Comment by robmadole** [comment]
I'll get the README updated. Thanks @david-driscoll for this.

**Pull request merged**
