### PR TITLE
 fix Vue warning during development

### PR DESCRIPTION
**Pull request by hungphongbk**
fix "[Vue warn]: Invalid prop: custom validator check failed for prop "size"" during development when using default value of "size"

### CODE REVIEW

**Comment by robmadole** [comment]
Thanks @hungphongbk for taking the time. However the documentation doesn't look quite right. Can you give this another look?

**Comment by alant** [comment]
@hungphongbk I only moved one import from a .js file to .vue file so it won't give me import but never used warning. Is it possible that commit 32cb8f3 is causing the issue? What exactly is the issue with documentation content?

**Comment by robmadole** [comment]
Alrighty, well we'll be happy to get this merged if the documentation issue can be cleaned up.

**Comment by robmadole** [comment]
@alant take a look at the GitHub preview of the markdown. The syntax is incorrect for the changed section.

**Comment by alant** [comment]
@robmadole sorry I took a look at https://github.com/hungphongbk/vue-fontawesome/blob/fa96dd5524ed49a29d254b798ab381593594010d/README.md and clicked around to check the markdown. I don't see the incorrect syntax. Is it possible to take a screenshot for what error you see? Thanks!

**Pull request closed without merging**
